### ISSUE TITLE
Publish on Github/F-Droid?

### ISSUE THREAD

**Issue by IzzySoft** [friimaind/pi-hole-droid#13]
As the project is open source: would you consider publishing the `.apk` here at Github (preferably with the corresponding `releases/`), so folks without Playstore can grab it? I'd then offer to pick and regularly update it with [my F-Droid compatible repository](https://android.izzysoft.de/repo), so it would be easily available even while not (yet?) listed with the official repo.

**Comment by friimaind** [comment]
Sure, it could be good for users without Google Play Store.

Currently I'm waiting for F-Droid because they are working to understand how manage Apache Cordova applications to be compiled into F-Droid repo:

- [My request for packaging](https://gitlab.com/fdroid/rfp/issues/48)
- [Discussion with F-Droid's team for Apache Cordova applications](https://forum.f-droid.org/t/making-cordova-easier/150)

I could copy the apk inside /releases/ with relative SHA checksum, for example:

`/releases/pihole-droid-101.apk`
`/releases/pihole-droid-102.apk`

Inside the folder there will be a single file SHA256SUMS like:

`thehashofthefile pihole-droid-101.apk`
`thehashofthefile2 pihole-droid-102.apk`

do you have some advice? :)

**Comment by IzzySoft** [comment]
I was rather thinking you could simply attach them to the corresponding release, see [Creating Releases](https://help.github.com/articles/creating-releases/) in the GitHub Help. If you'd do that, I have the possibility to automatically pick up updates (check runs about once every 24h).

No harm to have it in both repos in the end (while if you prefer, I would remove it from mine once it's available in the official repo): the variant in my repo would be "cross-updateable" with the Playstore version (as it uses your signature), while F-Droid uses its own signature. To my experience, it can take quite a while until a new project is picked up for the official repo :)

**Comment by friimaind** [comment]
Oh great, I didn't notice that I can attach binary files to releases, thank you for the tip.

I will attach the apk at every new release, please have a look at the latest 1.02 to see the apk https://github.com/friimaind/pi-hole-droid/releases

I see that I can automatize the process, I will look further into.

Honestly for me is not a problem to have the app in both repositories.
Pease let me know if I can close the issue! ;)

**Comment by IzzySoft** [comment]
Thanks a lot! Find it [here](https://apt.izzysoft.de/fdroid/index/apk/friimaind.piholedroid) now (feel free to link it from the `README.md`). As it's solved, I'll close the issue now. Feel free to ping me (issue still monitored) in case of any further questions – and thumbs up!

Oh, btw: Also included your app [here](https://android.izzysoft.de/applists/category/named/remotedroid_servermon#group_719) :smile_cat:
